### ISSUE TITLE
adding autotls causes build to fail

### ISSUE THREAD

**Issue by gun1x** [gin-gonic/autotls#14]
The moment I add autotls to gin gonic, I get this:
```
build asdasd: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/home/gunix/.go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/home/gunix/.go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)
```
Seems to be the same issue as [this one](https://github.com/gin-gonic/gin/issues/1673), however it appears only if I add `github.com/gin-gonic/autotls` to the project.

**Comment by sh7dm** [comment]
This comment can help you: https://github.com/gin-gonic/gin/issues/1673#issuecomment-482023570

**Comment by gun1x** [comment]
I am not actively using gin in any projects, as I found `net/http` actually has everything I need. I still consider gin gonic to be awesome, but I am going to close this ticket.
