### ISSUE TITLE
https handshake failed.

### ISSUE THREAD

**Issue by MrSong0607** [gin-gonic/autotls#5]
i run my server like buttom
![image](https://user-images.githubusercontent.com/13636643/38123362-38bba75c-340d-11e8-8229-9292d20e6aec.png)

i got this error like title in my browser
console log is 
![image](https://user-images.githubusercontent.com/13636643/38123443-9578f3dc-340d-11e8-882b-fa05281584eb.png)

**Comment by appleboy** [comment]
I will take it.

**Comment by SimplySerenity** [comment]
I'm seeing the same error, while using the manager as well.
