### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by dryswabbie** [gin-gonic/autotls#9]
Recommend tagging a new release now, and then after each cycle.

Not having the last release tagged caused problems vendoring autotls via the dep tool.

Turns out this project has a single outdated tagged release which the dep tool defaults to over the latest master branch.

Work-around to enable vendoring is to manually set the constraint in Gopakg.toml to:

    [[constraint]]
      branch = "master"
      name = "github.com/gin-gonic/autotls"

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
https://github.com/gin-gonic/autotls/releases/tag/0.0.2
